# Generated by Django 3.2.9 on 2022-10-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20221020_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='due_date',
            field=models.DateField(verbose_name='Дата дедлайна'),
        ),
    ]
