# Generated by Django 3.2.9 on 2022-10-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='GoalComment',
        ),
    ]
