# Generated by Django 3.2.9 on 2022-10-24 14:28

from django.db import migrations
from django.db import migrations, transaction
from django.utils import timezone


def create_objects(apps, schema_editor):
	"""
	Для загрузки кода моделей используется специальный метод apps.get_model
	Он позволяет загрузить ровно то состояние модели, которое было на момент применения этой миграции
	Импортировать настоящие классы – плохая практика
	так как в будущем вы можете удалить/переименовать эти модели, и тогда у вас будут ошибки импорта
	"""

	User = apps.get_model("core", "User")
	Board = apps.get_model("goals", "Board")
	BoardParticipant = apps.get_model("goals", "BoardParticipant")
	GoalCategory = apps.get_model("goals", "GoalCategory")

	with transaction.atomic():  # Применяем все изменения одной транзакцией
		for user in User.objects.all():  # Для каждого пользователя
			current_date_time = timezone.now()
			new_board = Board.objects.create(
				title="Мои цели",
				created=current_date_time,  # Проставляем вручную по той же причине, что описана вверху
				updated=current_date_time
			)
			BoardParticipant.objects.create(
				user=user,
				board=new_board,
				role=1,  # Владелец, проставляем числом, не импортируем код по той же причине
				created=current_date_time,
				updated=current_date_time
			)

			# проставляем всем категориям пользователя его доску
			GoalCategory.objects.filter(user=user).update(board=new_board)


class Migration(migrations.Migration):

	dependencies = [
		('goals', '0007_auto_20221024_1720'),
	]

	operations = [
		migrations.RunPython(create_objects)
	]
