# Generated by Django 3.2.9 on 2022-11-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Username пользователя в tg'),
        ),
    ]
