# Generated by Django 3.2.9 on 2022-11-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_tguser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='username',
            field=models.CharField(max_length=50, null=True, verbose_name='Username пользователя в tg'),
        ),
    ]
